### ISSUE TITLE
MN39:3.5 and elsewhere in this sutta; Aditi; Audible spaces after a "v" in various words (as if she has hiccough).

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#92]
* MN39:3.5 "Ārocayāmi vo, bhikkhave, paṭivedayāmi vo, bhikkhave:"—in "vo" and in the last "bhikkhave" in this segment. Similar in other (identical) segments in this sutta. Some of the words also occur in other segments of this sutta and have the same issue there.
* MN39:4.2 "bhavissati", "vivaṭo", and "chiddavā"; repeatedly in other (identical) segments in this sutta.
* MN39:7.2 "ājīvo"

**Comment by firepick1** [comment]
This is fixed in v1.4.4.

It affects ALL of Aditi's "v" words. So basically eVerything.
Please update staging before testing. Assigniing to Anagarika...

**Comment by sabbamitta** [comment]
All of the above instances sound fine now, except for "bhikkhave"—which now sounds wrong *everywhere*! Unfortunately it occurs in virtually every sutta at least once, in many suttas it occurs many times. In MN 39 it occurs almost in every segment, and in some more than once—so this is very disturbing.

**Comment by firepick1** [comment]
Fixed in v1.4.5. I changed all the "ve" words.

**Comment by sabbamitta** [comment]
This "v" problem seems to be messing things up. Now the following:
* MN38:3.5 "āvuso" sounds as if two letters are pronounced at the same time.
* Similar for "vuttaṃ" MN38:3.10.
* kevaṭṭaputto", for example MN38:3.11: Even if not directly a "v" problem, it obviously appeared after working on the "v"s. It sounds as if between kevaṭṭa" and "putto" a "r" is inserted.

**Comment by firepick1** [comment]
Fixed in v1.4.12

**Comment by sabbamitta** [comment]
These words still don't sound like they did before we worked on the "v" issues; but this doesn't affect the clarity of understanding—just doesn't sound as nice any more as it used to do... so I close the issue.
